# DATA
longread: test/test_ONT.fastq  # Path to Nanopore or pacbio long reads, all long reads should be in a fastq file

illumina:
    R1: data/Illumina_S1_L001_R1_001.fastq.gz  # Path to Illumina R1 reads
    R2: data/Illumina_S1_L001_R2_001.fastq.gz  # Path to Illumina R2 reads

# REQUIREMENT
genomesize: 100000  #extimate genome size in base pair

# LONGREAD TYPE
readtype: ONT  #nanopore:ONT, pacbio:pb

# PATH
sourceDir: PathToSourceDir
outputDir: PathToOutputDir
