# DATA
nanopore: data/rawdata.fastq  # Path to Nanopore reads
pacbio: data/pacbio_reads_combined.fastq.gz  # Path to Pacbio reads
illumina:
    R1: data/51226_S1_L001_R1_001.fastq.gz  # Path to Illumina R1 reads
    R2: data/51226_S1_L001_R2_001.fastq.gz  # Path to Illumina R2 reads

# REQUIREMENT
genomesize: 700000  #extimate genome size in base pair

# LONGREAD TYPE
readtype: ONT  #nanopore:ONT, pacbio:pb

# BLAST START GENE SEQUENCE
startGene: script/start_gene.fa

#RESOURCE 
